import { Chakra_Petch } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/global/Navbar';

const chakraPetch = Chakra_Petch({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={chakraPetch.className}>
              <header>
                <Navbar />
              </header>
              <main>
                {children}
              </main>
            </body>
        </html>
    );
}
