import { Chakra_Petch } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/global/Navbar';
import { Providers } from '@/context/Providers';

const chakraPetch = Chakra_Petch({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth">
            <head>
                <style>{`
                    body {
                        background-color: #0C1523;
                        margin: 0;
                        padding: 0;
                        font-family: ${chakraPetch.className};
                    }
                `}</style>
            </head>
            
            <body className={chakraPetch.className}>
            <Providers >
              <header>
                <Navbar />
              </header>
              <main className=''>
                {children}
              </main>
              </Providers>
            </body>
            
        </html>
    );
}
